### ISSUE TITLE
find_referents factors are not always organized by target rotation names

### ISSUE THREAD

**Issue by gitz13** [MateusPsi/esemComp#5]
I appreciate you designing this package, it makes the model estimation considerably more straightforward.

I wanted post that the factor numbers in the find_referents are not necessarily in the same order as the target rotation. My target rotation specified factor 1, factor 2, factor 3, and factor 4. When I ran an esem_efa model with 4 factors and the loadings outputed as factor 2, factor 4, factor 3, and factor 1. So when finding the referents, the factor names need to correspond to the output form esem_efa.

Can you include a step in the find_referents that matches the correct loadings to the correct factors? Or highlight the need to do this for future users? I suspect this is a discrepancy in the output being saved from the GPArotation dependency but feel providing feedback on a new package is always helpful to future users, even if not resolved.

**Comment by MateusPsi** [comment]
Hi gitz!

You are right. The output of `esem_efa()` is not in the same order as the supplied target matrix. That happens because the `psych::efa()` organizes the output by explained variance.

This is already acknowledged in the  [package vignette](https://mateuspsi.github.io/esemComp/articles/esem-within-cfa.html) (second paragraph in ESEM-within-CFA). It is also indicated in the [help](https://mateuspsi.github.io/esemComp/reference/find_referents.html) for `find_referents()`.
You think that, for completion, it would be nice to add this info to the documentation of `esem_efa()` too?

**Comment by gitz13** [comment]
Hi MateusPsi,

Adding it there would be helpful. Also you might consider rewritting the details in the find_referents() as the interpretation of the current details is a bit ambiguous. I ended up figure out the solution on my own by simply change the names in the factor name vector, after inspected the loadings based on the vignette.
